name: Permasnap build job

on:
  
  push:
    branches:
      - action!

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  environment-setup:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - run: npm install -g @ionic/cli
    
    - name: Install dependencies
      run: |
        npm install

    - name: Build Android APK
      working-directory: ./android
      run: bash ./gradlew assembleDebug

    - name: Build iOS IPA
      working-directory: ./ios/App
      run: xcodebuild -workspace App.xcworkspace -scheme App build -configuration debug -sdk iphoneos CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_IDENTITY="" CODE_SIGN_ENTITLEMENTS=""
      
