name: Permasnap build job

on:
  
  push:
    branches:
      - action!

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: macos-latest
    env:
      working-directory: ./permasnap-client
      CI: false
    
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - run: npm install -g @ionic/cli
    - run: npm install

    - run: ionic cap sync
      
    - name: Build iOS IPA
      run: cd ios/App && xcodebuild -workspace App.xcworkspace -scheme App clean -configuration debug -sdk iphoneos 

    - name: Build Android APK
      run: cd android/ && bash ./gradlew assembleDebug



